version: "3"
services:
  backend:
    container_name: backend
    build:
      context: ./backend/.
    networks:
      - mynetwork
    expose:
      - 8080
    ports:
      - "8080:8080"
    volumes:
      - backend_volume:/usr/src/app
    depends_on:
      - mariadb
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    networks:
      - mynetwork
    env_file:
      - ./backend/.env
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306

  dashboard:
    container_name: dashboard
    build:
      context: ./dashboard/.
    networks:
      - mynetwork
    ports:
      - "3000:3000"
    volumes:
      - dashboard_volume:/usr/src/app
    depends_on:
      - backend

volumes:
  backend_volume:
    driver: local
    driver_opts:
      type: "none"
      o: 'bind'
      device: './src/backend/'

  dashboard_volume:
    driver: local
    driver_opts:
      type: "none"
      o: 'bind'
      device: './src/dashboard/app/'
  mariadb_data:

networks:
  mynetwork:
    driver: bridge

# /home/aaitouna/e_commerce_dashboard/src
# /home/aaitouna/e_commerce_dashboard/src
