version: "3"
services:
  backend:
    container_name: backend
    build:
      context: ./backend/.
    networks:
      - mynetwork
    expose:
      - 8080
    ports:
      - "8080:8080"
    volumes:
      - backend_volume:/usr/src/app
    depends_on:
      - postgres

  dashboard:
    container_name: dashboard
    build:
      context: ./dashboard/.
    networks:
      - mynetwork
    ports:
      - "3000:3000"
    volumes:
      - dashboard_volume:/usr/src/app
    depends_on:
      - backend

  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      - mynetwork
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - backend/.env
volumes:
  backend_volume:
    driver: local
    driver_opts:
      type: "none"
      o: 'bind'
      device: '/home/aaitouna/e_commerce_dashboard/src/backend/'

  dashboard_volume:
    driver: local
    driver_opts:
      type: "none"
      o: 'bind'
      device: '/home/aaitouna/e_commerce_dashboard/src/dashboard/app/'
  postgres_data:


networks:
  mynetwork:
    driver: bridge
# /home/aaitouna/e_commerce_dashboard/src
# /home/aaitouna/e_commerce_dashboard/src